const int SIMILAR_SQUARES_DISTANCE = 20;

//const int THRESHOLD_LEVEL_TO_ALLOCATE_CHECKED_CHECKBOX = 100;
const int MIN_CHECKBOX_AREA = 1000;
const int SIMILAR_CHECKBOXES_DISTANCE = 15;

const int TEXT_ANSWER = -2;
const int NO_ANSWER = -1;
